import { state } from '@angular/animations';
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { CookieService } from 'ngx-cookie-service';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  user_credentials: any;

  constructor( private http:HttpClient, private router: Router,private cookieService:CookieService) { }
  statelist: any[] = ["Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Puducherry"]
  citylist: any = {
    "Andaman and Nicobar Islands": [
      'Nicobar',
      'North and Middle Andaman',
      'South Andaman'
    ],
    "Andhra Pradesh": [
      "Adilabad",
      "Anantapur",
      "Chittoor",
      "Kakinada",
      "Guntur",
      "Hyderabad",
      "Karimnagar",
      "Khammam",
      "Krishna",
      "Kurnool",
      "Mahbubnagar",
      "Medak",
      "Nalgonda",
      "Nizamabad",
      "Ongole",
      "Hyderabad",
      "Srikakulam",
      "Nellore",
      "Visakhapatnam",
      "Vizianagaram",
      "Warangal",
      "Eluru",
      "Kadapa",
    ],
    "Arunachal Pradesh": [
      "Anjaw",
      "Changlang",
      "East Siang",
      "Kurung Kumey",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Subansiri",
      "Papum Pare",
      "Tawang",
      "Tirap",
      "Dibang Valley",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
    ],
    "Assam": [
      "Baksa",
      "Barpeta",
      "Bongaigaon",
      "Cachar",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dima Hasao",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Marigaon",
      "Nagaon",
      "Nalbari",
      "Sibsagar",
      "Sonitpur",
      "Tinsukia",
      "Udalguri",
    ],
    "Bihar": [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
      "Chandigarh",
    ],
    "Chandigarh": [
      'Chandigarh'
    ],
    "Chhattisgarh": [
      "Bastar",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Jashpur",
      "Janjgir-Champa",
      "Korba",
      "Koriya",
      "Kanker",
      "Kabirdham (Kawardha)",
      "Mahasamund",
      "Narayanpur",
      "Raigarh",
      "Rajnandgaon",
      "Raipur",
      "Surguja",
    ],
    "Dadra and Nagar Haveli": [
      "Dadra and Nagar Haveli"
    ],
    "Daman and Diu": [
      "Daman",
      "Diu",
    ],
    "Delhi": [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "South Delhi",
      "South West Delhi",
      "West Delhi",
    ],
    "Goa": [
      "North Goa",
      "Panaji",
      "South Goa"
    ],
    "Gujarat": [
      "Ahmedabad",
      "Amreli district",
      "Anand",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Dahod",
      "The Dangs",
      "Gandhinagar",
      "Jamnagar",
      "Junagadh",
      "Kutch",
      "Kheda",
      "Mehsana",
      "Narmada",
      "Navsari",
      "Patan",
      "Panchmahal",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surendranagar",
      "Surat",
      "Vyara",
      "Vadodara",
      "Valsad",
    ],
    "Haryana": [
      "Ambala",
      "Bhiwani",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hissar",
      "Jhajjar",
      "Jind",
      "Karnal",
      "Kaithal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamuna Nagar",
    ],
    "Himachal Pradesh": [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul and Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
    ],
    "Jammu and Kashmir": [
      "Anantnag",
      "Badgam",
      "Bandipora",
      "Baramulla",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kishtwar",
      "Kupwara",
      "Kulgam",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajauri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
    ],
    "Jharkhand": [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
    "Karnataka": [
      "Bagalkot",
      "Bangalore Rural",
      "Bangalore Urban",
      "Belgaum",
      "Bellary",
      "Bidar",
      "Bijapur",
      "Chamarajnagar",
      "Chikkamagaluru",
      "Chikkaballapur",
      "Chitradurga",
      "Davanagere",
      "Dharwad",
      "Dakshina Kannada",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri district",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysore",
      "Raichur",
      "Shimoga",
      "Tumkur",
      "Udupi",
      "Uttara Kannada",
      "Ramanagara",
      "Yadgir",
    ],
    "Kerala": [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thrissur",
      "Thiruvananthapuram",
      "Wayanad",
    ],
    "Madhya Pradesh": [
      "Alirajpur",
      "Anuppur",
      "Ashok Nagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa (East Nimar)",
      "Khargone (West Nimar)",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Rewa",
      "Rajgarh",
      "Ratlam",
      "Raisen",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
    "Maharashtra": [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Bhandara",
      "Beed",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai suburban",
      "Nandurbar",
      "Nanded",
      "Nagpur",
      "Nashik",
      "Osmanabad",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sindhudurg",
      "Sangli",
      "Solapur",
      "Satara",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
    "Manipur": [
      "Bishnupur",
      "Churachandpur",
      "Chandel",
      "Imphal East",
      "Senapati",
      "Tamenglong",
      "Thoubal",
      "Ukhrul",
      "Imphal West",
    ],
    "Meghalaya": [
      "East Garo Hills",
      "East Khasi Hills",
      "Jaintia Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "West Garo Hills",
      "West Khasi Hills",
    ],
    "Mizoram": [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Serchhip",
    ],
    "Nagaland": [
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Mon",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
    "Odisha": [
      "Angul",
      "Boudh (Bauda)",
      "Bhadrak",
      "Balangir",
      "Bargarh (Baragarh)",
      "Balasore",
      "Cuttack",
      "Debagarh (Deogarh)",
      "Dhenkanal",
      "Ganjam",
      "Gajapati",
      "Jharsuguda",
      "Jajpur",
      "Jagatsinghpur",
      "Khordha",
      "Kendujhar (Keonjhar)",
      "Kalahandi",
      "Kandhamal",
      "Koraput",
      "Kendrapara",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nuapada",
      "Nayagarh",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Subarnapur (Sonepur)",
      "Sundergarh",
    ],
    "Puducherry": [
      "Karaikal",
      "Mahe",
      "Pondicherry",
      "Yanam",
    ],
    "Punjab": [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Firozpur",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Sri Muktsar Sahib",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Ajitgarh (Mohali)",
      "Sangrur",
      "Nawanshahr",
      "Tarn Taran",
    ],
    "Rajasthan": [
      "Ajmer",
      "Alwar",
      "Bikaner",
      "Barmer",
      "Banswara",
      "Bharatpur",
      "Baran",
      "Bundi",
      "Bhilwara",
      "Churu",
      "Chittorgarh",
      "Dausa",
      "Dholpur",
      "Dungapur",
      "Ganganagar",
      "Hanumangarh",
      "Jhunjhunu",
      "Jalore",
      "Jodhpur",
      "Jaipur",
      "Jaisalmer",
      "Jhalawar",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sikar",
      "Sawai Madhopur",
      "Sirohi",
      "Tonk",
      "Udaipur",
    ],
    "Sikkim": [
      "East Sikkim",
      "North Sikkim",
      "South Sikkim",
      "West Sikkim",
    ],
    "Tamil Nadu": [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Madurai",
      "Nagapattinam",
      "Nilgiris",
      "Namakkal",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Tirupur",
      "Tiruchirappalli",
      "Theni",
      "Tirunelveli",
      "Thanjavur",
      "Thoothukudi",
      "Tiruvallur",
      "Tiruvarur",
      "Tiruvannamalai",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
    "Telangana": [
      'Adilabad',
      'Bhadradri Kothagudem',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Jayashankar Bhoopalpally',
      'Jogulamba Gadwal',
      'Kamareddy',
      'Karimnagar',
      'Khammam',
      'Komaram Bheem Asifabad',
      'Mahabubabad',
      'Mahabubnagar',
      'Mancherial',
      'Medak',
      'Medchal',
      'Nagarkurnool',
      'Nalgonda',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Rajanna Sircilla',
      'Rangareddy',
      'Sangareddy',
      'Siddipet',
      'Suryapet',
      'Vikarabad',
      'Wanaparthy',
      'Warangal (Rural)',
      'Warangal (Urban)',
      'Yadadri Bhuvanagiri',
    ],
    "Tripura": [
      "Dhalai",
      "North Tripura",
      "South Tripura",
      "Khowai",
      "West Tripura",
    ],
    "Uttar Pradesh": [
      "Agra",
      "Allahabad",
      "Aligarh",
      "Ambedkar Nagar",
      "Auraiya",
      "Azamgarh",
      "Barabanki",
      "Budaun",
      "Bagpat",
      "Bahraich",
      "Bijnor",
      "Ballia",
      "Banda",
      "Balrampur",
      "Bareilly",
      "Basti",
      "Bulandshahr",
      "Chandauli",
      "Chhatrapati Shahuji Maharaj Nagar",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Kanshi Ram Nagar",
      "Etawah",
      "Firozabad",
      "Farrukhabad",
      "Fatehpur",
      "Faizabad",
      "Gautam Buddh Nagar",
      "Gonda",
      "Ghazipur",
      "Gorakhpur",
      "Ghaziabad",
      "Hamirpur",
      "Hardoi",
      "Mahamaya Nagar",
      "Jhansi",
      "Jalaun",
      "Jyotiba Phule Nagar",
      "Jaunpur district",
      "Ramabai Nagar (Kanpur Dehat)",
      "Kannauj",
      "Kanpur",
      "Kaushambi",
      "Kushinagar",
      "Lalitpur",
      "Lakhimpur Kheri",
      "Lucknow",
      "Mau",
      "Meerut",
      "Maharajganj",
      "Mahoba",
      "Mirzapur",
      "Moradabad",
      "Mainpuri",
      "Mathura",
      "Muzaffarnagar",
      "Panchsheel Nagar district (Hapur)",
      "Pilibhit",
      "Shamli",
      "Pratapgarh",
      "Rampur",
      "Raebareli",
      "Saharanpur",
      "Sitapur",
      "Shahjahanpur",
      "Sant Kabir Nagar",
      "Siddharthnagar",
      "Sonbhadra",
      "Sant Ravidas Nagar",
      "Sultanpur",
      "Shravasti",
      "Unnao",
      "Varanasi",
    ],
    "Uttarakhand": [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
    "West Bengal": [
      "Birbhum",
      "Bankura",
      "Bardhaman",
      "Darjeeling",
      "Dakshin Dinajpur",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Cooch Behar",
      "Kolkata",
      "Maldah",
      "Paschim Medinipur",
      "Purba Medinipur",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "South 24 Parganas",
      "Purulia",
      "Uttar Dinajpur",
    ],
  }
  getcitylist(state: any | null) {
    this.cities = this.citylist[state];
  }
  cities: any;
  details: any={};


  registerForm: FormGroup = new FormGroup({
    fn: new FormControl(this.details.name, Validators.required),
    age: new FormControl(this.details.age, [Validators.min(5), Validators.max(100), Validators.required]),
    dob: new FormControl(this.details.dob, Validators.required),
    class: new FormControl(this.details.grade, Validators.required),
    course: new FormControl(this.details.course, Validators.required),
    email: new FormControl(this.details.email, [Validators.required, Validators.email]),
    mobile: new FormControl(this.details.mobile, [Validators.required, Validators.pattern('[- +()0-9]+'), Validators.minLength(10)]),
    address: new FormControl(this.details.address),
    city: new FormControl(this.details.city, Validators.required),
    state: new FormControl(this.details.state, Validators.required),
  });
  ngOnInit(): void {

    if (this.cookieService.get('user')) {
      // console.log(JSON.parse(this.cookieService.get('user')))
      this.user_credentials = JSON.parse(this.cookieService.get('user'))
      this.http.post<any>('https://server.srymak.com/get_stu_d', {
        email: this.user_credentials.email, passw: atob(this.user_credentials.password)
      }).subscribe((data) => {
        if (data.success == true) {
          console.log(data.details)
          this.details = data.details;
          this.getcitylist(this.details.state)
          this.registerForm = new FormGroup({
            fn: new FormControl(this.details.name, Validators.required),
            age: new FormControl(this.details.age, [Validators.min(5), Validators.max(100), Validators.required]),
            dob: new FormControl(this.details.dob, Validators.required),
            class: new FormControl(this.details.grade, Validators.required),
            course: new FormControl(this.details.course, Validators.required),
            email: new FormControl(this.details.email, [Validators.required, Validators.email]),
            mobile: new FormControl(this.details.mobile, [Validators.required, Validators.pattern('[- +()0-9]+'), Validators.minLength(10)]),
            address: new FormControl(this.details.address),
            city: new FormControl(this.details.city, Validators.required),
            state: new FormControl(this.details.state, Validators.required),
          });
        }
      })
    } else {
      this.router.navigate(['home'])
    }

  }

  UPDATE_USER() {
    this.http.post<any>('https://server.srymak.com/update_user', {
      email: this.registerForm.controls.email.value,
      password: atob(JSON.parse(this.cookieService.get('user')).password),
      fn: this.registerForm.controls.fn.value,
      mobile: this.registerForm.controls.mobile.value,
      ln: '',
      class: this.registerForm.controls.class.value,
      course: this.registerForm.controls.course.value,
      state: this.registerForm.controls.state.value,
      dob: this.registerForm.controls.dob.value,
      age: this.registerForm.controls.age.value,
      address: this.registerForm.controls.address.value,
      city: this.registerForm.controls.city.value,
    }).subscribe((data) => {
      if (data.success == false) {
      } else {
        this.cookieService.set('user-details-t-y-u-i-i', data.details);
        this.router.navigate(['dashboard']);

      }
    })
  }
  onlyNumberKey(evt: any) {

    // Only ASCII character in that range allowed
    var ASCIICode = (evt.which) ? evt.which : evt.keyCode
    if (evt.which != 8 && evt.which != 0 && evt.which < 48 || evt.which > 57)
      return false;
    return true;
  }

}
